config/routes.rb
Rails.application.routes.draw do

  resources :beneficiarios
  resources :bancos
  resources :centros
  resources :fontes
  resources :fornecedors
  resources :orcamentos
  resources :atuals, except: [:index, :show, :destroy]
  resources :transferencias
  #devise_for :users, :skip => [:registrations]
  devise_for :users
  resources :anos
  resources :contas
  resources :grupoconts
  get 'home/index'
  root 'home#index'
  
  
  resources :lancamentos do
   resources :pagamentos do
    resources :nenes, only: [:create]
   end
 end



get 'pagamentos/:id', controller: 'lancamentos', action: 'pagamentos', as: 'pagamento'

get 'sessions', controller: 'application', action: 'set_session'

  namespace :relatorios do
   get 'orcamentos/receitas_geral'
   get 'orcamentos/despesas_geral'
   get 'orcamentos/orcamento_geral'
   get 'contas/apagar'
   get 'contas/areceber'
   get 'bancos/extratos'
   get 'compara/despesas'
   get 'compara/receitas'
   get 'compara/gastos'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/beneficiario.rb
class Beneficiario < ApplicationRecord
  belongs_to :user
  has_many :pagamentos
  has_many :benes
end

app/controllers/beneficiarios_controller.rb
class BeneficiariosController < ConfigsController 
  before_action :set_beneficiario, only: [:show, :edit, :update, :destroy]

  # GET /beneficiarios
  # GET /beneficiarios.json
  def index
    @beneficiarios = Beneficiario.usuario(current_user)
  end

  # GET /beneficiarios/1
  # GET /beneficiarios/1.json
  def show
  end

  # GET /beneficiarios/new
  def new
    @beneficiario = Beneficiario.new
  end

  # GET /beneficiarios/1/edit
  def edit
  end

  # POST /beneficiarios
  # POST /beneficiarios.json
  def create
    @beneficiario = Beneficiario.new(beneficiario_params)

    respond_to do |format|
      if @beneficiario.save
        format.html { redirect_to beneficiarios_path, notice: 'Beneficiario Criado com Sucesso.' }
        format.json { render :show, status: :created, location: @beneficiario }
      else
        format.html { render :new }
        format.json { render json: @beneficiario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beneficiarios/1
  # PATCH/PUT /beneficiarios/1.json
  def update
    respond_to do |format|
      if @beneficiario.update(beneficiario_params)
        format.html { redirect_to beneficiarios_path, notice: 'Beneficiario Atualizado com Sucesso.' }
        format.json { render :show, status: :ok, location: @beneficiario }
      else
        format.html { render :edit }
        format.json { render json: @beneficiario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beneficiarios/1
  # DELETE /beneficiarios/1.json
  def destroy
    @beneficiario.destroy
    respond_to do |format|
      format.html { redirect_to beneficiarios_url, notice: 'Beneficiario Removido com Sucessoe.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beneficiario
      @beneficiario = Beneficiario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beneficiario_params
      params.require(:beneficiario).permit(:nome, :ativo).merge(user_id: current_user.id)
    end
end

app/views/beneficiarios/_form.html.erb
<%= simple_form_for(@beneficiario) do |f| %>
	<%= error_messages_for(@beneficiario) %>
	<div class="form-row justify-content-center">
	  <div class="col-sm-12 col-md-12 col-lg-6">
	    <div class="form_group">
    		<%= f.input :nome %>

	    </div>
	    <%= f.input :ativo %>
		<hr>
	    <%= btn_save %>
	    <%= btn_cancel(beneficiarios_path) %>
	</div>
</div>



<% end %>

app/views/beneficiarios/edit.html.erb
<% @card_title = "Edição de beneficiario" %>
<%= render "form", beneficiario: @beneficiario %>

app/views/beneficiarios/index.html.erb
<% @card_title = "Relação de Beneficiario" %>
<% @btn_new = btn_new(new_beneficiario_path) %>

<div class="table-responsive">
  <%= table_for(@beneficiarios) do %>
    <% field_table('Nome') { |f| f.nome} %>
    <% field_table('Situação') { |f| situacao(f.ativo)} %>
    <% btn_for %>

  <% end %>
</div>

app/views/beneficiarios/new.html.erb
<% @card_title = "Novo Registro de beneficiario" %>
<%= render "form", beneficiario: @beneficiario %>

app/views/beneficiarios/show.html.erb
<% @card_title = "Listagem da beneficiario" %>

<p>
  <strong>Nome:</strong>
  <%= @beneficiario.nome %>
</p>

<p>
  <strong>Ativo:</strong>
  <%= situacao(@beneficiario.ativo) %>
</p>


<%= btn_edit(edit_beneficiario_path(@beneficiario)) %> | 
<%= btn_back(beneficiarios_path) %>