config/routes.rb
Rails.application.routes.draw do

  resources :beneficiarios
  resources :bancos
  resources :centros
  resources :fontes
  resources :fornecedors
  resources :orcamentos
  resources :atuals, except: [:index, :show, :destroy]
  resources :transferencias
  #devise_for :users, :skip => [:registrations]
  devise_for :users
  resources :anos
  resources :contas
  resources :grupoconts
  get 'home/index'
  root 'home#index'
  
  
  resources :lancamentos do
   resources :pagamentos do
    resources :nenes, only: [:create]
   end
 end



get 'pagamentos/:id', controller: 'lancamentos', action: 'pagamentos', as: 'pagamento'

get 'sessions', controller: 'application', action: 'set_session'

  namespace :relatorios do
   get 'orcamentos/receitas_geral'
   get 'orcamentos/despesas_geral'
   get 'orcamentos/orcamento_geral'
   get 'contas/apagar'
   get 'contas/areceber'
   get 'bancos/extratos'
   get 'compara/despesas'
   get 'compara/receitas'
   get 'compara/gastos'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/conta.rb
class Conta < ApplicationRecord
	before_save :save_tipo
	belongs_to :user
	belongs_to :grupocont
	has_many :orcamentos, dependent: :destroy 
	
	validates_presence_of :nome, :grupocont, :ctipo
	validates_uniqueness_of :nome

	def save_tipo
	self.tipo = self.grupocont.tipo	
	end

	

end
 

app/controllers/contas_controller.rb
class ContasController < ConfigsController 
  before_action :set_conta, only: [:show, :edit, :update, :destroy]
  before_action :grupos_contas, only: [:edit, :new]
  before_action :ctipos, only: [:edit, :new]


include DataModule
include Enum

  
  # GET /contas
  # GET /contas.json

   def index
    @contas = Conta.usuario(current_user).order(:nome)
  end

  # GET /contas/1
  # GET /contas/1.json
  def show
  end

  # GET /contas/new
  def new
    @conta = Conta.new
  end

  # GET /contas/1/edit
  def edit
  end

  # POST /contas
  # POST /contas.json
  def create
    @conta = Conta.new(conta_params)

    respond_to do |format|
      if @conta.save
        format.html { redirect_to contas_path, notice: "Conta #{@conta.nome} Criado com Sucesso!" }
        format.json { render :show, status: :created, location: @conta }
      else
        format.html { render :new }
        format.json { render json: @conta.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contas/1
  # PATCH/PUT /contas/1.json
  def update
    respond_to do |format|
      if @conta.update(conta_params)
        format.html { redirect_to contas_path, notice: "Conta #{@conta.nome} Atualizada com Sucesso! "}
        format.json { render :show, status: :ok, location: @conta }
      else
        format.html { render :edit }
        format.json { render json: @conta.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contas/1
  # DELETE /contas/1.json
  def destroy
    @conta.destroy
    respond_to do |format|
      format.html { redirect_to contas_url, notice: "Conta #{@conta.nome} Removida com Sucesso!" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conta
      @conta = Conta.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def conta_params
      params.require(:conta).permit(:nome, :tipo, :ctipo, :ativo, :grupocont_id).merge(user_id: current_user.id)
    end
  
  end

app/controllers/relatorios/bancos_controller.rb
class Relatorios::BancosController < ConfigsController 

	def extratos
		if params[:mes].blank?
			params[:mes] = Time.new.month
		else	
			@mes = (params[:mes].to_i)
			@date = (Date.new(@anos_atual[0].ano,@mes,-1) - 1.month)
		end

		@pagamentos = Pagamento.usuario(current_user).search_banco(params[:mes], @anos_atual[0].ano, params[:bancos]).order('data')
		@saldo_pagamentos_anterior = Pagamento.usuario(current_user).where("data <= ? and banco_id = ?", (@date), params[:bancos]).order(:data)

		@lancamentos_receitas = Lancamento.usuario(current_user).escolha_tipo('Receita')
		@lancamentos_despesas = Lancamento.usuario(current_user).escolha_tipo('Despesa')

		if Rails.env.production?
			@pagamentos_receitas = Pagamento.usuario(current_user).escolha_tipo('Receita').where("extract(month from data) = #{params[:mes]} and extract(year from data) = #{@anos_atual[0].ano}").where(banco: params[:bancos])
			@pagamentos_despesas = Pagamento.usuario(current_user).escolha_tipo('Despesa').where("extract(month from data) = #{params[:mes]} and extract(year from data) = #{@anos_atual[0].ano}").where(banco: params[:bancos])
		else
			@pagamentos_receitas = Pagamento.usuario(current_user).escolha_tipo('Receita').where("cast(strftime('%m', data) as int) = #{params[:mes]} and cast(strftime('%Y', data) as int) = #{@anos_atual[0].ano}").where(banco: params[:bancos])
			@pagamentos_despesas = Pagamento.usuario(current_user).escolha_tipo('Despesa').where("cast(strftime('%m', data) as int) = #{params[:mes]} and cast(strftime('%Y', data) as int) = #{@anos_atual[0].ano}").where(banco: params[:bancos])

		end

		#Calculo do Saldo Anterior
		@saldo_anterior = 0
		@saldo_pagamentos_anterior.each do |s|
			s.tipo == 'Receita' ? (@saldo_anterior += s.total) : (@saldo_anterior -= s.total)
		end
	end
end

app/controllers/relatorios/compara_controller.rb
class Relatorios::ComparaController < ConfigsController 

	def despesas
	end

	def receitas
	end
	def gastos
		@pagamentos = Pagamento.joins(:lancamento).where(tipo: 0).where('beneficiario_id = ? OR  banco_id = ? OR lancamentos.centro_id = ?',  params[:beneficiario], params[:banco], params[:centro])
		@total = @pagamentos.sum(:total)
	end
end

app/controllers/relatorios/contas_controller.rb
class Relatorios::ContasController < ConfigsController 
	before_action :variables, only: [:apagar, :areceber]
	before_action :lancamentos_a_pagar, only: [:apagar]
	before_action :lancamentos_a_receber, only: [:areceber]


	include DataModule
	def apagar
	
		@total = @lancamentos_apagar.sum(&:valor)
	end
	def areceber
	end

	private

	def variables
		@avencer = 0
		@vencidas = 0
	end


end

app/controllers/relatorios/orcamentos_controller.rb
class Relatorios::OrcamentosController < ConfigsController 


	def receitas_geral
	end

	def despesas_geral
	end

	def orcamento_geral
	end

	def resumogruposreceitas
	end
end

app/views/relatorios/contas/apagar.html.erb
<% @card_title = "Relação de Contas à Pagar" %>


<% @btn_print = link_to "Imprimir", relatorios_contas_apagar_path(@lancamentos_apagar, format: :pdf, start: params[:start], end: params[:end], valor: params[:valor] ), target: "_blank", class: 'btn btn-warning float-right  mr-2' %>


<div class="card-header mb-3 bg-light p-1 " style="height:42px" align="center" >
	<%= form_tag( relatorios_contas_apagar_path, method: "get") do %>
	<%= date_field_tag :start, params[:start] %> <b>até</b>
	<%= date_field_tag :end, params[:end] %>

	<%= text_field_tag :valor, params[:valor], size: 8, placeholder: 'R$ 0,00' %>
	

	<%= button_tag(type: 'submit', class: 'btn btn-primary btn-sm', id: 'button', name: nil) do %>
	<i class="fa fa-search"></i>
	<% end %>
	<% end %>

	
</div> 
<%= @regis %>

<div class="table-responsive" data-controller='datatables'>

	<table  class="table table-bordered table-sm table-hover display" >
		<thead class= 'thead-light', align= 'center'>
			<tr>
				<th>Lancamento</th>
				<th>Grupo</th>
				<th>Descrição</th>
				<th>Valor</th>
				<th>Pago</th>
				<th>Resto</th>
				<th>Situação</th>
				<th style="width: 7%"></th>
				<th style="width: 7%"></th>
			</tr>
		</thead>
		<tbody>
			<% @lancamentos_apagar.each do |lancamento| %>

			<% if lancamento.data >= Date.today %>
			<% @avencer += ( lancamento.valor - lancamento.pagamentos.sum(:valor) ) %>
			<% end %>


			<% if lancamento.data < Date.today  %>
			<% @vencidas += ( lancamento.valor - lancamento.pagamentos.sum(:valor) ) %>
			<% end %>				



			<tr>
				<% if lancamento.valor <= lancamento.pagamentos.sum(:valor) %>

				<% else %>
				<td><%= data(lancamento.data) %></td>
				<td><%= lancamento.orcamento.conta.grupocont.nome %></td>
				<td><%= "#{lancamento.descricao} - #{lancamento.parcela}/#{ lancamento.number}" %></td>
				<td><%= valor(lancamento.valor) %></td>
				<td><%= valor(lancamento.pagamentos.sum(:valor)) %></td>
				<td><%= valor(lancamento.valor - lancamento.pagamentos.sum(:valor)) %></td>
				<td><%= vencimento(lancamento.data) %></td>

				<td><%= btn_show((lancamento), true) %>	</td>	
				<td><%= link_to  pagamento_path(lancamento), class: "btn btn-success btn-sm btn-icon-split", title: 'Realizar Pagamentos', remote: true do %>

					<span class="icon text-white-50">
						<i class="fas fa-wallet"></i>
					</span>
					<span class="text d-none d-lg-block d-xl-block">PAGMTS</span>

					<% end %></td>

					<% end %>

				</tr>
				<% end %>
			</tbody>
		</table>

	</div>

	<div class="mt-3 float-right mb-4">
		<strong>Total Vencidas: </strong> <%=  valor(@vencidas) %> <br>
		<strong>Total À Vencer: </strong> <%= valor(@avencer)%><br><hr>
		<strong>Total: </strong> <%= valor(@total)%>
	</div>
	<% session[:total_vencidas] = @vencidas %>
	<% session[:total_avencer] = @avencer %>
	<% session[:total] = @total %>

	<%= render partial: 'lancamentos/shared/modal' %>

app/views/relatorios/contas/areceber.html.erb
<% @card_title = "Relação de Contas à Receber" %>
<% @btn_imprimir =  btn_print(relatorios_contas_areceber_path(format: :pdf)) %>

<div class="table-responsive" data-controller='datatables'>

	<table  class="table table-bordered table-sm table-hover display">
		<thead class= 'thead-light', align= 'center'>
			<tr>
				<th>Lancamento</th>
				<th>Grupo</th>
				<th>Conta</th>
				<th>Descrição</th>
				<th>Valor</th>
				<th>Pago</th>
				<th>Resto</th>
				<th>Situação</th>
				<th style="width: 7%" colspan="2">Ação</th>
			</tr>
		</thead> 
		<tbody>
			<% @lancamentos_areceber.each do |lancamento| %>
			
			<% if lancamento.data >= Date.today  %>
			<% @avencer += ( lancamento.valor - lancamento.pagamentos.sum(:valor) ) %>
			<% end %>
			
			<% if lancamento.data < Date.today  %>
			<% @vencidas += ( lancamento.valor - lancamento.pagamentos.sum(:valor) ) %>
			
			<% end %>		
			<tr>
				<% if lancamento.valor <= lancamento.pagamentos.sum(:valor) %>

				<% else %>
				<td><%= data(lancamento.data) %></td>
				<td><%= lancamento.orcamento.conta.grupocont.nome %></td>
				<td><%= lancamento.orcamento.conta.nome %></td>
				<td><%= lancamento.descricao %></td>
				<td><%= valor(lancamento.valor) %></td>
				<td><%= valor(lancamento.pagamentos.sum(:valor)) %></td>
				<td><%= valor(lancamento.valor - lancamento.pagamentos.sum(:valor)) %></td>
				<td><%= vencimento(lancamento.data) %></td>
				
				<td><%= link_to  pagamento_path(lancamento), class: "btn btn-success btn-sm btn-icon-split", title: 'Realizar Pagamentos', remote: true do %>

					<span class="icon text-white-50">
						<i class="fas fa-wallet"></i>
					</span>
					<span class="text d-none d-lg-block d-xl-block">PAGMTS</span>

					<% end %>

				</td>	
						<td><%= btn_show((lancamento), true) %></td>

				<% end %>

			</tr>
			<% end %>
		</tbody>
	</table>
</div>



<div class="mt-3 float-right">
	<strong>Total Vencidas: </strong> <%=  valor(@vencidas) %> <br>
	<strong>Total À Vencer: </strong> <%= valor(@avencer)%><br><hr>
	<strong>Total: </strong> <%= valor(@avencer + @vencidas)%>
</div>
<% session[:total_vencidas] = @vencidas %>
<% session[:total_avencer] = @avencer %>
<% session[:total] = @avencer + @vencidas %>


<%= render partial: 'lancamentos/shared/modal' %>