config/routes.rb
Rails.application.routes.draw do

  resources :beneficiarios
  resources :bancos
  resources :centros
  resources :fontes
  resources :fornecedors
  resources :orcamentos
  resources :atuals, except: [:index, :show, :destroy]
  resources :transferencias
  #devise_for :users, :skip => [:registrations]
  devise_for :users
  resources :anos
  resources :contas
  resources :grupoconts
  get 'home/index'
  root 'home#index'
  
  
  resources :lancamentos do
   resources :pagamentos do
    resources :nenes, only: [:create]
   end
 end



get 'pagamentos/:id', controller: 'lancamentos', action: 'pagamentos', as: 'pagamento'

get 'sessions', controller: 'application', action: 'set_session'

  namespace :relatorios do
   get 'orcamentos/receitas_geral'
   get 'orcamentos/despesas_geral'
   get 'orcamentos/orcamento_geral'
   get 'contas/apagar'
   get 'contas/areceber'
   get 'bancos/extratos'
   get 'compara/despesas'
   get 'compara/receitas'
   get 'compara/gastos'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/concerns/layout.rb
module Layout
	def layout_by_resource
		if devise_controller?
			"devise"
		else
			"application"
		end
	end
end

app/views/layouts/menus/_cadastros.html.erb
<%= link_to " Grupos de Contas", grupoconts_path, class: " dropdown-item" %>
<%= link_to " Contas Pessoais", contas_path, class: "dropdown-item" %>
 <div class="dropdown-divider"></div>
<%= link_to " Fornecedores", fornecedors_path, class: "dropdown-item"  %>
<%= link_to " Fonte de Receitas", fontes_path, class: "dropdown-item"  %>
<%= link_to " Centros de Controle", centros_path, class: "dropdown-item"  %>
 <div class="dropdown-divider"></div>
<%= link_to " Beneficiários", beneficiarios_path, class: "dropdown-item"  %>
<%= link_to " Contas", bancos_path, class: "dropdown-item"  %>
<%= link_to " Gerar Anos", anos_path, class: "dropdown-item" %>

app/views/layouts/menus/_email.html.erb
<%= link_to	 destroy_user_session_path, method: :delete,  class: 'dropdown-item' do %>
<i class="fas fa-sign-out-alt"></i> Sair 
<% end %>

app/views/layouts/menus/_lancamentos.html.erb
<%= link_to " Orcamentos", orcamentos_path, class: "dropdown-item" %>
<%= link_to " Contas", lancamentos_path, class: "dropdown-item" %>
<div class="dropdown-divider"></div>

<%= link_to " Transações Bancárias", transferencias_path, class: "dropdown-item" %>

app/views/layouts/menus/_menus.html.erb
<nav class="navbar sticky-top  navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="/">SFIP</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navsite">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navsite">
    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" data-toggle="dropdown">Cadastros</a>
        <div class="dropdown-menu">
          <%= render partial: "layouts/menus/cadastros" %>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" data-toggle="dropdown">Lançamentos</a>
        <div class="dropdown-menu">
          <%= render partial: "layouts/menus/lancamentos" %>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" data-toggle="dropdown">
        Relatórios</a>
        <div class="dropdown-menu">
          <%= render partial: "layouts/menus/relatorios" %>
        </div>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto" >
     <li class="nav-item">
      <button type="button" class="btn btn-outline-light" data-toggle="modal" data-target="#ano_modal">
        
        <%= @select_btn_ano %>
    
     </button>


   </li>
   <li class="nav-item dropdown">
    
    <%= link_to '#', class: 'nav-link dropdown-toggle', id: 'navbarDropdown', data: { toggle: 'dropdown' } do %>
        <i class="far fa-user-circle"> </i> <%= current_user.email %>
    <% end %>

      <div class="dropdown-menu">

       <%= render partial: 'layouts/menus/email' %>
     </div>
   </li>
 </ul>
</div>
</nav>
<%= render partial: 'layouts/menus/modal_menus' %>

app/views/layouts/menus/_modal_menus.html.erb
<!-- Modal -->
<div class="modal fade" id="ano_modal" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Escolha o Ano</h5>
        
      </div>
      <div class="modal-body">

        <%= form_tag(sessions_path  , method: "get") do %>
        <%= select_tag :year_select, options_from_collection_for_select(Ano.usuario(current_user), "id", "anos", cookies.encrypted[:selected_year]), :style => "width: 100%" %>
        <div class="modal-footer">
          <%= button_tag(type: 'submit', class: 'btn btn-primary', id: 'button_banco', name: nil) do %>
          Salvar
        </div>
        <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/menus/_relatorios.html.erb
<%= link_to "Orçamento Geral", relatorios_orcamentos_orcamento_geral_path, class: "dropdown-item" %>
<%= link_to 'Orçamento das Receitas',  relatorios_orcamentos_receitas_geral_path, class: "dropdown-item" %>
<%= link_to 'Orçamento das Despesas',  relatorios_orcamentos_despesas_geral_path, class: "dropdown-item"%>

<div class="dropdown-divider"></div>
<%= link_to 'Contas à Pagar', relatorios_contas_apagar_path, class: "dropdown-item"  %>

<%= link_to 'Contas à Receber', relatorios_contas_areceber_path	, class: "dropdown-item"  %>


<div class="dropdown-divider"></div>
<%= link_to 'Extrato de Contas', relatorios_bancos_extratos_path, class: "dropdown-item"  %>
<%#= link_to 'Resumos', 'resumogruposreceitas_path', class: "dropdown-item disabled"  %>
<div class="dropdown-divider"></div>
<%= link_to 'Despesas Prevista X Realizadas',  relatorios_compara_despesas_path , class: "dropdown-item"  %>
<%= link_to 'Receitas Prevista X Realizadas', relatorios_compara_receitas_path, class: "dropdown-item"  %>
<div class="dropdown-divider"></div>
<%= link_to 'Gastos por Tipo', relatorios_compara_gastos_path , class: "dropdown-item"  %>