config/routes.rb
Rails.application.routes.draw do

  resources :beneficiarios
  resources :bancos
  resources :centros
  resources :fontes
  resources :fornecedors
  resources :orcamentos
  resources :atuals, except: [:index, :show, :destroy]
  resources :transferencias
  #devise_for :users, :skip => [:registrations]
  devise_for :users
  resources :anos
  resources :contas
  resources :grupoconts
  get 'home/index'
  root 'home#index'
  
  
  resources :lancamentos do
   resources :pagamentos do
    resources :nenes, only: [:create]
   end
 end



get 'pagamentos/:id', controller: 'lancamentos', action: 'pagamentos', as: 'pagamento'

get 'sessions', controller: 'application', action: 'set_session'

  namespace :relatorios do
   get 'orcamentos/receitas_geral'
   get 'orcamentos/despesas_geral'
   get 'orcamentos/orcamento_geral'
   get 'contas/apagar'
   get 'contas/areceber'
   get 'bancos/extratos'
   get 'compara/despesas'
   get 'compara/receitas'
   get 'compara/gastos'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ano.rb
class Ano < ApplicationRecord
	belongs_to :user
	has_many :orcamentos, dependent: :destroy
	has_many :lancamentos
	
	validates_presence_of :ano
	validates_uniqueness_of :ano, scope: :user_id
	
def ativo_nome
	ativo? ? "Aberto" : "Fechado"
end

	def anos
		"#{ano} - #{ativo_nome}"
	end
end

app/controllers/anos_controller.rb
class AnosController < ConfigsController 
  before_action :set_ano, only: [:show, :edit, :update, :destroy]

  # GET /anos
  # GET /anos.json
  def index
    @anos = Ano.usuario(current_user)
  end

  # GET /anos/1
  # GET /anos/1.json
  def show
  end

  # GET /anos/new
  def new
    @ano = Ano.new
  end

  # GET /anos/1/edit
  def edit
  end

  # POST /anos
  # POST /anos.json
  def create
    @ano = Ano.new(ano_params)

    respond_to do |format|
      if @ano.save
        format.html { redirect_to anos_path, notice: 'Ano Criado com Sucesso.' }
        format.json { render :show, status: :created, location: @ano }
      else
        format.html { render :new }
        format.json { render json: @ano.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /anos/1
  # PATCH/PUT /anos/1.json
  def update
    respond_to do |format|
      if @ano.update(ano_params)
        format.html { redirect_to anos_path, notice: 'Ano Atualizado com Sucesso.' }
        format.json { render :show, status: :ok, location: @ano }
      else
        format.html { render :edit }
        format.json { render json: @ano.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /anos/1
  # DELETE /anos/1.json
  def destroy
    @ano.destroy
    respond_to do |format|
      format.html { redirect_to anos_url, notice: 'Ano Apagado com Sucesso.' }
      format.json { head :no_content }
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ano
      @ano = Ano.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ano_params
      params.require(:ano).permit(:ano, :ativo).merge(user_id: current_user.id)
    end
  end

app/views/anos/_form.html.erb
<% @card_title = 'Cadastro de Anos' %>

<%= simple_form_for(@ano) do |f| %>
	<div class="col-sm-6">
		<div class="form-group">
			<%= f.input :ano,  collection: (Date.current.year-2)..(Date.current.year+10), include_blank: false, input_html: {data: {controller: 'select2'} } %>
			<%= f.input :ativo, class:"form-control", placeholder:"Digite o ativo" %>
		</div>
		<%= btn_save %>
		<%= btn_cancel(anos_path) %>
	</div>
<% end %>

app/views/anos/edit.html.erb
<% @card_title = "Edição de ano" %>
<%= render "form", ano: @ano %>

app/views/anos/index.html.erb
<% @card_title = "Relação de " + @anos.model_name.human(count: 2) %>
<% @btn_new = btn_new(new_ano_path) %>

<div class="table-responsive">
  <%= table_for(@anos, 'index') do %>
    <% field_table('Ano') { |f| f.ano} %>
    <% field_table('Situação') { |f| situacao(f.ativo)} %>
    <% btn_for %>
  <% end %>
</div>

app/views/anos/new.html.erb
<% @title_painel = "Novo Registro de ano" %>
<%= render "form", ano: @ano %>

app/views/anos/show.html.erb
<% @title_painel = "Listagem do ano" %>

<p>
  <strong>Ano:</strong>
  <%= @ano.ano %>
</p>

<p>
  <strong>Ativo:</strong>
  <%= situacao(@ano.ativo) %>
</p>




<%= btn_edit(edit_ano_path(@ano)) %> | 
<%= btn_back(anos_path) %>